### ISSUE TITLE
Can you check or give advice

### ISSUE THREAD

**Issue by bert-il** [pguth/peermesh#4]
I cloned yesterday (12-Feb-2018), installes locally nodejs Version 9.5.0 and got this error:
bertil@debian4:~/peertransfer$ /home/bertil/local/bin/node /usr/bin/npm start

> peertransfer@2.1.0 start /home/bertil/peertransfer
> [[ $NODE_EVN = production ]] && npm run prod || npm run dev

sh: 1: [[: not found

> peertransfer@2.1.0 dev /home/bertil/peertransfer
> signalhub listen -p 7000 & budo --live --host localhost index.js:bundle.js -- -t envify

events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::7000
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1496:7)
    at listen (/home/bertil/peertransfer/node_modules/signalhub/bin.js:48:10)
    at Object.<anonymous> (/home/bertil/peertransfer/node_modules/signalhub/bin.js:24:28)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
[0000] info  Server running at http://localhost:9966/ (connect)
[0001] info  LiveReload running
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'envify' from '/home/bertil/peertransfer'
    at /home/bertil/peertransfer/node_modules/resolve/lib/async.js:48:31
    at processDirs (/home/bertil/peertransfer/node_modules/resolve/lib/async.js:182:39)
    at ondir (/home/bertil/peertransfer/node_modules/resolve/lib/async.js:197:13)
    at load (/home/bertil/peertransfer/node_modules/resolve/lib/async.js:80:43)
    at onex (/home/bertil/peertransfer/node_modules/resolve/lib/async.js:105:17)
    at /home/bertil/peertransfer/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:166:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertransfer@2.1.0 dev: `signalhub listen -p 7000 & budo --live --host localhost index.js:bundle.js -- -t envify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peertransfer@2.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bertil/.npm/_logs/2018-02-11T23_39_27_165Z-debug.log

npm ERR! Linux 4.9.0-4-amd64
npm ERR! argv "/home/bertil/local/bin/node" "/usr/bin/npm" "start"
npm ERR! node v9.5.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertransfer@2.1.0 start: `[[ $NODE_EVN = production ]] && npm run prod || npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peertransfer@2.1.0 start script '[[ $NODE_EVN = production ]] && npm run prod || npm run dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertransfer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     [[ $NODE_EVN = production ]] && npm run prod || npm run dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertransfer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertransfer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bertil/peertransfer/npm-debug.log
bertil@debian4:~/peertransfer$ 
Any hint to resolve this kind of problem / issue?

**Comment by perguth** [comment]
Should be fixed in https://github.com/perguth/peertransfer/commit/4f2a9ea6278a6df4203cf30532a1d38db16e3224
